[package]
name = "zniff-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
quick-xml = {version="0.38.3", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6.0"
serialport = "4.7.3"
